# Fedora builds are implemented but are disabled until we decide we
# need them; Travis limits our number of concurrent jobs so we don't
# want more than are necessary.
# The Fedora docker images are "fedora:26" and "fedora:27"

# Also, the following gram tests failed for all fedora versions:
#   nonblocking-register-test.pl, register-callback-test.pl, register-test.pl
jobs:
  include:

    - &run_tests
      # Template; subsequent uses modify 'env'
      env:
        - IMAGE=centos:centos6 TASK=tests COMPONENTS=udt,myproxy,ssh
      stage: test
      sudo: required
        - IMAGE=centos:centos7 TASK=tests COMPONENTS=gram5
      services:
        - docker

      before_install:
        - sudo apt-get update
        - sleep 5
        - sudo docker pull ${IMAGE}

      script:
      - travis-ci/setup_tasks.sh
    - <<: *run_tests
      env:
        - IMAGE=centos:centos7 TASK=tests COMPONENTS=udt,myproxy,ssh
    - <<: *run_tests
      env:
        - IMAGE=centos:centos6 TASK=tests COMPONENTS=gram5
    - <<: *run_tests
      env:
        - IMAGE=centos:centos7 TASK=tests COMPONENTS=gram5

    - stage: deploy
      env:
        - IMAGE=centos:centos7 TASK=srpms
      sudo: required
      services:
        - docker

      before_install:
        - sudo apt-get update
        - sleep 5
        - sudo docker pull ${IMAGE}

      script:
      - travis-ci/setup_tasks.sh
      deploy:
        on:
          tags: true
          all_branches: true
        skip_cleanup: true
        file_glob: true
        provider: releases
        overwrite: true
        # ^ this doesn't actually work but I'm leaving it in there in
        #   case it gets fixed later
        api_key:
          secure: ndqiULdDgGzxuFQmqDmgC6OmtXKLIowqOTJRPSoLCMBIPPbZf68bTcEjbWdwqnTKz9V/YyigWkQO55M/FH5ZzG8Y/olK3NObr/GebGkyCOEDdM4LHL1rt/1kmxENpFZidVO9bxMbkj+cgaJKU9pJ6VJ7jbXYpP6hj2imVm2KQZIAOvynGYFiSleZmgnmqMJw7yRXxaGOtXyHwV8mc17MPVM2dnMUXPEta7RIRJzLy/gInxHnZzQwZ4EDIDhUTxgeeqMVV6AInQJzsg7xUJsgv7IEvYm3bfqZJz5NkYh1izABDJBNDwJac8osaicllhVmLjwr9k2QSLCchyIiR/BzB0ciKqsxBzo6fpF03e1kkiqIxMdLWHLOiWV092OJLjqdrUZReLlnpYf45Uvwv0gQuX9sYAgR9xLunxmyTjXr5WUkqtIPSA8OchSuvbNOIHB9BqJ+rt4Ejt54ZYNtUUdHhqaB3q7PJSdUnbOesoaVqQYgPo6rDuh3wR16kahkhPAslkuTTbYw2b5ZUapaN1fiZpMQfqGdWvaNiIU6Esata05ANoKnu/QORSfZkTydIYEPtROGpDNkC94nTRcfWcxTOySft6cXjB5OyAelnaV6mq6h+lgz4NBNnIOh1yIMenjpgu118p2NmYgZejpf+DtmKpm6RpmJFkcW0AKwe9qcjDk=
        file: travis_deploy/*

# vim:ft=yaml:sw=2:sts=2:et
